# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pacific Youth Track Cycling Tournament 2016
email: info@pacifictrackcycling.com.au
description: >
  A premier international youth track cycling competition for U15 –U17 boys and girls proudly presented to you by Track Cycling WA and National Cycling Centre WA
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.pacifictrackcycling.com.au" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
